### ISSUE TITLE
No vocab.pkl file exits

### ISSUE THREAD

**Issue by Shandilya21** [shubhamagarwal92/mmd#11]
Traceback (most recent call last):
  File "train.py", line 327, in <module>
    main(args)
  File "train.py", line 154, in main
    vocab = pkl.load(open(args.vocab_path,'rb'))[1]
IOError: [Errno 2] No such file or directory: '/home1/mauzama/Arunav/mmd_courteous_final/data/v2/dialogue_data//context_2__20//vocab.pkl'

**Comment by shubhamagarwal92** [comment]
Can you check the `vocab_path` that you provided to the model? Be careful about the extra `_` in your folder name `context_2__20 `

**Comment by Shandilya21** [comment]
Thanks yeah, I got that. I am looking for the JSON file, i find the search_criteria and compulsory fields are not there. have you changed your dataset. I have downloaded the data from the saha.et.al drive (v2) for train the model?

**Comment by githwd2016** [comment]
In fact, there are no **search_criteria** or **compulsory** fields in the data from the saha.et.al. I have met this problem. Maybe saha.et.al have changed their dataset.

**Comment by Shandilya21** [comment]
@githwd2016 , Did you open any PR related to that?. the data-set is different and these mentioned attribute are missing in public mmd dataset.

**Comment by githwd2016** [comment]
@Shandilya21 , I just use the data provided by @shubhamagarwal92. Maybe you could recover the fields from the data. Related issue. #8

**Comment by Shandilya21** [comment]
@githwd2016 Thanks, i am trying with @shubhamagarwal92 data set for context_2 and context_5.

**Comment by Shandilya21** [comment]
@githwd2016 the datasets provided by @shubhamagarwal92  i.e., [link](https://www.dropbox.com/s/yz31j1zd3vvjwrw/data.zip?dl=0) contains search_criterion and compulsory_fields?
