### ISSUE TITLE
Global name HRED is not defined in translate.py

### ISSUE THREAD

**Issue by Shandilya21** [shubhamagarwal92/mmd#13]
Hi,
@shubhamagarwal92  @githwd2016 
Can you help me for solving this issues, i have checked the line of error and model_type for opt.model_type, it takes all the parameters but after complete training, the following error raise:

Traceback (most recent call last):
  File "translate.py", line 207, in <module>
    main(args)
  File "translate.py", line 105, in main
    model = HRED(src_vocab_size=vocab_size,
NameError: global name 'HRED' is not defined

Thanks for help in advance

**Comment by shubhamagarwal92** [comment]
In relation to PR #10. 

@githwd2016 could you confirm if this is related to [imports](https://github.com/shubhamagarwal92/mmd/blob/master/translate.py#L24)

Should it be then:
```
from mmd.modules.models import *
```

**Comment by Shandilya21** [comment]
Hi,
Initially it was commented out. But i uncommented it and run the train_and_translate for 1 epochs,  should i need change to 
   * from mmd.modules.models import *
   * #10 comment out the getattr from the code

Thanks
