### ISSUE TITLE
some issues in data processing

### ISSUE THREAD

**Issue by khoaipx** [shubhamagarwal92/mmd#2]
There are some issues in data processing:

- I downloaded dataset and extracted it into the data folder (_$PROJECT_DIR/data_). For detail, the data folder is like below:
```
mmd/data
├── dataset
   ├── v1
   │   ├── test
   │   ├── train
   │   └── valid
   └── v2
       ├── test
       ├── train
       └── valid
```
But when I run `dialogue_data.sh`, it didn't work. I looked at your code. I think we should fix at line [31](https://github.com/shubhamagarwal92/mmd/blob/master/data_processing/dialogue_data.sh#L31).
`export DATA_DIR=$PARENT_DIR/data/` --> `export DATA_DIR=$PARENT_DIR/data/dataset/$DATA_VERSION`

- Besides, in file `train_and_translate.sh`, at line [54](https://github.com/shubhamagarwal92/mmd/blob/master/train_and_translate.sh#L54), the default config is `_v4`, but in your code, you wrote `_v5`.

Anw, thank you so much for pytorch version of MMD.

**Comment by shubhamagarwal92** [comment]
1. Thanks for noting that. I will update the `$DATA_DIR` path.
2. You can provide the config version when prompted. I will also update the default version. (I can also provide you other config versions that I tried.)  

Let me know if you face any other issues or want me to upload the data

**Comment by khoaipx** [comment]
If I want to re-produce the baseline result (in the paper `Amrita Saha et. al., Towards Building Large Scale Multimodal Domain-Aware Conversation Systems, 2017`), please tell me how to config.

**Comment by shubhamagarwal92** [comment]
As we noted in the paper, as well as in this [issue](https://github.com/amritasaha1812/MMD_Code/issues/3), we are not able to achieve BLEU of 56.67 that they report in the paper. With their config, dataset and code, we got a BLEU of 37.67.

**Comment by shubhamagarwal92** [comment]
Hi @khoaipx 

Please see the commit 503b48173ea2d13e113e04dcb2179d8737b0298b.

I have uploaded the data that I used [here](https://www.dropbox.com/s/yz31j1zd3vvjwrw/data.zip?dl=0). It contains the versions for both context 2 and context 5 and authors (Shah et al. version). Unzip and put in data folder. Please take care of the file paths. 

Also, I have uploaded sample config to run our code on their version of data.

**Comment by shubhamagarwal92** [comment]
Closing for now. Reopen if you face any other issues. I will also appreciate if you have PRs related to issues with file path. :)
