### ISSUE TITLE
Guidance for changing image feature extractor

### ISSUE THREAD

**Issue by hardik2396** [shubhamagarwal92/mmd#4]
I want to change image feature extractor from VGG-16 to Resnet 50 or something.  

Thanks in advance.

**Comment by shubhamagarwal92** [comment]
Hi Hardik,

In the pickle dataset that we use, each image is assigned a file path (hard coded by Shah et al.) and we use the annoy index to retrieve the image vectors (based on this file path) as done by Shah et al.

You would have to:
1. Align the image path with their actual urls from raw meta data. 
2. Crawl the images from the web
3. Run any image extractor ([pytorch](https://pytorch.org/docs/stable/torchvision/models.html#torchvision.models.resnet152) provides direct api for that) and save it in (like h5) files. Or you can pass the raw image pixel values and extend the [image_encoder](https://github.com/shubhamagarwal92/mmd/blob/master/modules/image_encoder.py) if you want to fine tune as well.

**Comment by hardik2396** [comment]
Thank you very much for your guidance.
