### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by khoaipx** [shubhamagarwal92/mmd#5]
Dear @shubhamagarwal92,

There are some compile errors:
- You didn't declare param _args_ for function _evaluate_ at line [64](https://github.com/shubhamagarwal92/mmd/blob/master/train.py#L64) but called it at line [106](https://github.com/shubhamagarwal92/mmd/blob/master/train.py#L106).
- At line [87](https://github.com/shubhamagarwal92/mmd/blob/master/modules/models.py#L87), [Bridge class](https://github.com/shubhamagarwal92/mmd/blob/master/modules/bridge.py) only has 2 params hidden size of encoder and decoder, but you declared 3 arguments: hidden size of encoder, decoder and activation function.
- Besides, I got some troubles with 2 KB Encoders. I tried to run _train_and_translate_shah_et_al.sh_. It means that I didn't use kb encoders, but they were initialized. However, param _vocab_size_ was assigned None value.

I think you should re-run your code with all configurations to guarantee that your code works well.

Thank you so much for your supporting.

**Comment by shubhamagarwal92** [comment]
Resolved with #9. Thanks @githwd2016 :)

**Comment by shubhamagarwal92** [comment]
Closing this now. Please re-open if it still persists.
